### ISSUE TITLE
Unexpected error thrown in a working gurnt file

### ISSUE THREAD

**Issue by imalhasaranga** [drewzboto/grunt-connect-proxy#95] opened 2015-04-22 10:52 UTC
Recently one of my colleague clone the working branch and tried to run it.. but unexpectedly when grunt is loading this error throws 

$ grunt serve
Loading "connect_proxy.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined

Running "serve" task
Warning: Task "configureProxies" not found. Use --force to continue.

Aborted due to warnings.

but at that time my clone was working fine and I did not have any changes to the grunt, to understand the status I removed my  node_modules folder and  run the command 

npm install   within the project folder and after that I'm seeing the same issue 

Is this a bug ? I'm having latest node installed

**Comment by esseti** [comment] 2015-04-22 11:10
I used yo to create a angular project yesteday and it worked and still work.
I tried today and i've the same problem as this issue.

So it could be that something got updated over the night and breaks the compatibility.

**Comment by esseti** [comment] 2015-04-22 11:15
I noticed that the one which works has `eventemitter3@0.1.6` while the other `eventemitter3@1.0.0` can be this?

**Comment by dzmitry-kankalovich** [comment] 2015-04-22 11:26
Same issue here, same clues about eventemitter

**Comment by imalhasaranga** [comment] 2015-04-22 11:28
@esseti  Indeed that is the issue... thanks man issue fixed :+1: ,  hopefully this will fixed soon

**Comment by ruiaraujo** [comment] 2015-04-22 11:35
@imalhasaranga I would leave this open until it is actually fixed.

The real solution for this project would be to update the http-proxy dependency to the latest version which has eventemitter pinned.

**Comment by dzmitry-kankalovich** [comment] 2015-04-22 11:36
@ruiaraujo I will definitely agree with you, just check this out: https://github.com/nodejitsu/node-http-proxy/blob/v1.1.6/package.json#L20

**Comment by dzmitry-kankalovich** [comment] 2015-04-22 11:37
@imalhasaranga please reopen issue, workaround found, but not the real solution.

**Comment by imalhasaranga** [comment] 2015-04-22 11:47
Sorry guys..

**Comment by ruiaraujo** [comment] 2015-04-22 11:48
I have written a PR to fix the issue.

In the meanwhile, just use the fork with patch applied since it may take a while until it is merged.
Just place this line on your package.json
"grunt-connect-proxy": "git://github.com/ruiaraujo/grunt-connect-proxy#patch-1",

**Comment by mtraynham** [comment] 2015-04-22 15:11
@ruiaraujo Thanks!

**Comment by mtraynham** [comment] 2015-04-22 16:00
@ruiaraujo After skimming, I think this repo is probably dead...  Anyone willing to fork/rename/push to npm?

**Comment by MrHus** [comment] 2015-04-22 17:55
For the interested: the issue is that EventEmitter3 exports itself like so:

``` JavaScript
module.exports = EventEmitter;
```

And it is required in http-proxy as: 

``` JavaScript
EE3     = require('eventemitter3').EventEmitter,
```
There exists no 'EventEmitter' key as EventEmitter it is the 'export' itself so that line should be:

``` JavaScript
EE3     = require('eventemitter3'),
```

**Comment by fidel-karsto** [comment] 2015-04-23 08:26
@MrHus is right. And for the even more interested, this seems to be the reason behind why things broke yesterday:

* node-http-proxy declared its dependency (until version 1.7.2) to EventEmitter3 with an asterisk instead a semantic version pattern [s. commit](https://github.com/nodejitsu/node-http-proxy/commit/81874f795b7df7929e03d9d4cb98a947b1ef114b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
* Everything worked without any problems until yesterday when EventEmitter3 pushed to version 1.0.0 with the breaking changes mentioned by @MrHus [s. commit](https://github.com/primus/eventemitter3/commit/43211e9a9050887530421e8e2d8b9e1aa2506cc4#diff-168726dbe96b3ce427e7fedce31bb0bc)
* node-http-proxy fixed their package.json to pattern 0.x.x with version 1.7.2
* Therefore the fix for grunt-connect-proxy would be to push the dependency for http-proxy from ~1.1.4 to ~1.7.2

**Comment by drewzboto** [comment] 2015-04-23 08:34
sorry i haven't a lot of time to work on this repo. if anyone wants admin access, let me know and i'll assign it

**Closed** 2015-04-23 08:34 UTC

**Comment by fidel-karsto** [comment] 2015-04-23 10:36
@drewzboto could you update the version to 0.1.12 and update the sources on npm as well?

**Comment by matthieubulte** [comment] 2015-04-23 10:39
we have a couple of nice PR easy to merge and then we can release.

unless someone else has time to release now.

**Comment by ruiaraujo** [comment] 2015-04-23 10:48
@matthieubulte I think we should tag 0.2.0 and release it ASAP since it is breaking people's builds.

**Comment by fidel-karsto** [comment] 2015-04-23 10:52
@ruiaraujo :+1:

**Comment by drewzboto** [comment] 2015-04-23 10:53
@ruiaraujo I added you as a npm collaborator incase you wanted to push immediately.

**Comment by drewzboto** [comment] 2015-04-23 10:54
Sounds like @matthieubulte prefers to wait until #76 is merged though before bumping the version

**Comment by ruiaraujo** [comment] 2015-04-23 10:55
@drewzboto Thanks. I will check that PR since I have a setup where it happens a lot.

**Comment by Valkendorm** [comment] 2015-04-23 15:27
@ruiaraujo Many thanks for that fix.

**Comment by fidel-karsto** [comment] 2015-04-23 15:35
@ruiaraujo thanks :+1: :beers:

**Comment by ruiaraujo** [comment] 2015-04-23 18:16
@fidel-karsto I will send you the address for the beer. Augustiner bitte! ;)

**Comment by fidel-karsto** [comment] 2015-04-23 19:08
@ruiaraujo excellent choice! ;)

**Comment by ojacquemart** [comment] 2015-04-23 22:09
@ruiaraujo Thanks :+1:. Great job!

**Comment by chfw** [comment] 2015-05-21 13:52
@esseti +1, your solution works. Is this already fixed in newer releases? It is strange that one PC(running fedora 16) among 4 had this problem.

**Comment by devsakshiagarwal** [comment] 2015-09-29 09:13
@esseti thanks, it worked. :)

**Comment by fantastao** [comment] 2015-10-16 03:54
@esseti thanks for the solution!

**Comment by esseti** [comment] 2015-10-16 07:36
it should have been fixed.
